/**
 * Physical and astronomical constants.
 *
 * Sources: CODATA 2018 recommended values (NIST, https://physics.nist.gov/cuu/Constants/),
 * where c, h, e, k_B and N_A are exact by the 2019 SI redefinition; IAU 2015 Resolution B3
 * nominal solar values; IAU 2012 Resolution B2 (astronomical unit).
 */
import { Rational } from "../core/rational";

export interface ConstantDef {
  symbol: string;
  latex: string;
  name: string;
  value: string; // decimal string (exact rational when `exact`)
  unit: string;
  exact: boolean;
  uncertainty?: string;
  source: string;
}

export const CONSTANTS: Record<string, ConstantDef> = {
  c: {
    symbol: "c",
    latex: "c",
    name: "Kecepatan cahaya dalam vakum",
    value: "299792458",
    unit: "m/s",
    exact: true,
    source: "SI 2019 (definisi)",
  },
  h: {
    symbol: "h",
    latex: "h",
    name: "Konstanta Planck",
    value: "6.62607015e-34",
    unit: "J*s",
    exact: true,
    source: "SI 2019 (definisi)",
  },
  e_charge: {
    symbol: "e",
    latex: "e",
    name: "Muatan elementer",
    value: "1.602176634e-19",
    unit: "C",
    exact: true,
    source: "SI 2019 (definisi)",
  },
  k_B: {
    symbol: "k_B",
    latex: "k_B",
    name: "Konstanta Boltzmann",
    value: "1.380649e-23",
    unit: "J/K",
    exact: true,
    source: "SI 2019 (definisi)",
  },
  N_A: {
    symbol: "N_A",
    latex: "N_A",
    name: "Bilangan Avogadro",
    value: "6.02214076e23",
    unit: "1/mol",
    exact: true,
    source: "SI 2019 (definisi)",
  },
  R: {
    symbol: "R",
    latex: "R",
    name: "Konstanta gas ideal",
    value: Rational.parseDecimal("6.02214076e23")!
      .mul(Rational.parseDecimal("1.380649e-23")!)
      .toFixedString(30),
    unit: "J/(mol*K)",
    exact: true,
    source: "R = N_A·k_B (eksak)",
  },
  F: {
    symbol: "F",
    latex: "F",
    name: "Konstanta Faraday",
    value: Rational.parseDecimal("6.02214076e23")!
      .mul(Rational.parseDecimal("1.602176634e-19")!)
      .toFixedString(30),
    unit: "C/mol",
    exact: true,
    source: "F = N_A·e (eksak)",
  },
  G: {
    symbol: "G",
    latex: "G",
    name: "Konstanta gravitasi",
    value: "6.67430e-11",
    unit: "m^3/(kg*s^2)",
    exact: false,
    uncertainty: "0.00015e-11",
    source: "CODATA 2018",
  },
  g_n: {
    symbol: "g",
    latex: "g",
    name: "Percepatan gravitasi standar",
    value: "9.80665",
    unit: "m/s^2",
    exact: true,
    source: "CGPM 1901 (nilai konvensional)",
  },
  epsilon_0: {
    symbol: "epsilon_0",
    latex: "\\varepsilon_0",
    name: "Permitivitas vakum",
    value: "8.8541878128e-12",
    unit: "F/m",
    exact: false,
    uncertainty: "0.0000000013e-12",
    source: "CODATA 2018",
  },
  mu_0: {
    symbol: "mu_0",
    latex: "\\mu_0",
    name: "Permeabilitas vakum",
    value: "1.25663706212e-6",
    unit: "N/A^2",
    exact: false,
    uncertainty: "0.00000000019e-6",
    source: "CODATA 2018",
  },
  k_e: {
    symbol: "k_e",
    latex: "k_e",
    name: "Konstanta Coulomb 1/(4πε₀)",
    value: "8.9875517923e9",
    unit: "N*m^2/C^2",
    exact: false,
    source: "Diturunkan dari ε₀ CODATA 2018",
  },
  m_e: {
    symbol: "m_e",
    latex: "m_e",
    name: "Massa elektron",
    value: "9.1093837015e-31",
    unit: "kg",
    exact: false,
    uncertainty: "0.0000000028e-31",
    source: "CODATA 2018",
  },
  m_p: {
    symbol: "m_p",
    latex: "m_p",
    name: "Massa proton",
    value: "1.67262192369e-27",
    unit: "kg",
    exact: false,
    uncertainty: "0.00000000051e-27",
    source: "CODATA 2018",
  },
  m_n: {
    symbol: "m_n",
    latex: "m_n",
    name: "Massa neutron",
    value: "1.67492749804e-27",
    unit: "kg",
    exact: false,
    uncertainty: "0.00000000095e-27",
    source: "CODATA 2018",
  },
  u: {
    symbol: "u",
    latex: "u",
    name: "Satuan massa atom",
    value: "1.66053906660e-27",
    unit: "kg",
    exact: false,
    uncertainty: "0.00000000050e-27",
    source: "CODATA 2018",
  },
  sigma_SB: {
    symbol: "sigma",
    latex: "\\sigma",
    name: "Konstanta Stefan–Boltzmann",
    value: "5.670374419e-8",
    unit: "W/(m^2*K^4)",
    exact: false,
    source:
      "CODATA 2018 (secara definisi eksak dari h, k, c; di sini dibulatkan ke 10 angka penting)",
  },
  b_W: {
    symbol: "b",
    latex: "b",
    name: "Konstanta pergeseran Wien",
    value: "2.897771955e-3",
    unit: "m*K",
    exact: false,
    source:
      "CODATA 2018 (secara definisi eksak dari h, k, c; di sini dibulatkan ke 10 angka penting)",
  },
  R_inf: {
    symbol: "R_inf",
    latex: "R_\\infty",
    name: "Konstanta Rydberg",
    value: "10973731.568160",
    unit: "1/m",
    exact: false,
    uncertainty: "0.000021",
    source: "CODATA 2018",
  },
  a_0: {
    symbol: "a_0",
    latex: "a_0",
    name: "Jari-jari Bohr",
    value: "5.29177210903e-11",
    unit: "m",
    exact: false,
    uncertainty: "0.00000000080e-11",
    source: "CODATA 2018",
  },
  atm: {
    symbol: "atm",
    latex: "p_0",
    name: "Tekanan atmosfer standar",
    value: "101325",
    unit: "Pa",
    exact: true,
    source: "Definisi",
  },
  au: {
    symbol: "au",
    latex: "\\mathrm{au}",
    name: "Satuan astronomi",
    value: "149597870700",
    unit: "m",
    exact: true,
    source: "IAU 2012 Resolusi B2",
  },
  R_sun: {
    symbol: "R_sun",
    latex: "R_\\odot",
    name: "Jari-jari Matahari (nominal)",
    value: "6.957e8",
    unit: "m",
    exact: true,
    source: "IAU 2015 Resolusi B3 (nilai nominal)",
  },
  L_sun: {
    symbol: "L_sun",
    latex: "L_\\odot",
    name: "Luminositas Matahari (nominal)",
    value: "3.828e26",
    unit: "W",
    exact: true,
    source: "IAU 2015 Resolusi B3 (nilai nominal)",
  },
  GM_sun: {
    symbol: "GM_sun",
    latex: "GM_\\odot",
    name: "Parameter gravitasi Matahari (nominal)",
    value: "1.3271244e20",
    unit: "m^3/s^2",
    exact: true,
    source: "IAU 2015 Resolusi B3 (nilai nominal)",
  },
  M_sun: {
    symbol: "M_sun",
    latex: "M_\\odot",
    name: "Massa Matahari",
    value: "1.98841e30",
    unit: "kg",
    exact: false,
    source: "GM☉ (IAU 2015) / G (CODATA 2018)",
  },
  M_earth: {
    symbol: "M_earth",
    latex: "M_\\oplus",
    name: "Massa Bumi",
    value: "5.97217e24",
    unit: "kg",
    exact: false,
    source: "GM⊕ = 3.986004e14 m³/s² (IAU 2015) / G (CODATA 2018)",
  },
  R_earth: {
    symbol: "R_earth",
    latex: "R_\\oplus",
    name: "Jari-jari ekuator Bumi (nominal)",
    value: "6.3781e6",
    unit: "m",
    exact: true,
    source: "IAU 2015 Resolusi B3 (nilai nominal)",
  },
};
