/**
 * Formula registry for physics, chemistry, astronomy, engineering and geometry.
 *
 * Each formula is stored once as an equation string; the formula solver can solve it for
 * any of its variables (symbolically when possible, otherwise after substitution), with
 * units converted to SI and dimensional consistency checked.
 * References point to open textbooks (OpenStax) rather than invented chapter numbers.
 */
import { REFERENCES } from "../steps/builder";
import type { Reference } from "../steps/types";

export type Constraint = "positive" | "nonnegative" | "angle" | "unit-interval" | "below-c" | "any";

export interface FormulaVariable {
  s: string;
  name: string;
  unit: string;
  latex?: string;
  constraint?: Constraint;
  /** Key into CONSTANTS: value is fixed (not solvable), shown in steps. */
  constant?: string;
  /** Default value (editable), e.g. g = 9.80665 m/s². */
  defaultValue?: string;
}

export type FormulaDomain = "fisika" | "kimia" | "astronomi" | "teknik" | "geometri";

export interface FormulaDef {
  id: string;
  name: string;
  domain: FormulaDomain;
  topic: string;
  equation: string;
  variables: FormulaVariable[];
  description: string;
  assumptions?: string[];
  reference: Reference;
  example: { solveFor: string; values: Record<string, string> };
}

const P1 = REFERENCES.openstaxPhysics1;
const P2 = REFERENCES.openstaxPhysics2;
const P3 = REFERENCES.openstaxPhysics3;
const CH = REFERENCES.openstaxChem;
const AS = REFERENCES.openstaxAstro;
const AL = REFERENCES.openstaxAlgebra;

const v = (
  s: string,
  name: string,
  unit: string,
  extra: Partial<FormulaVariable> = {},
): FormulaVariable => ({ s, name, unit, constraint: "any", ...extra });
const pos = (
  s: string,
  name: string,
  unit: string,
  extra: Partial<FormulaVariable> = {},
): FormulaVariable => v(s, name, unit, { constraint: "positive", ...extra });
const nonneg = (
  s: string,
  name: string,
  unit: string,
  extra: Partial<FormulaVariable> = {},
): FormulaVariable => v(s, name, unit, { constraint: "nonnegative", ...extra });
const angle = (s: string, name: string): FormulaVariable =>
  v(s, name, "°", { constraint: "angle", latex: s === "theta" ? "\\theta" : undefined });
const g = (): FormulaVariable =>
  pos("g", "percepatan gravitasi", "m/s^2", { defaultValue: "9.80665" });

export const FORMULAS: FormulaDef[] = [
  // ------------------------------------------------------------------ Kinematika
  {
    id: "glbb-kecepatan",
    name: "Kecepatan pada GLBB",
    domain: "fisika",
    topic: "Kinematika",
    equation: "v = v_0 + a*t",
    variables: [
      v("v", "kecepatan akhir", "m/s"),
      v("v_0", "kecepatan awal", "m/s"),
      v("a", "percepatan", "m/s^2"),
      nonneg("t", "waktu", "s"),
    ],
    description: "Gerak lurus berubah beraturan: kecepatan berubah linear terhadap waktu.",
    assumptions: ["Percepatan konstan."],
    reference: P1,
    example: { solveFor: "v", values: { v_0: "5", a: "2", t: "3" } },
  },
  {
    id: "glbb-perpindahan",
    name: "Perpindahan pada GLBB",
    domain: "fisika",
    topic: "Kinematika",
    equation: "s = v_0*t + 1/2*a*t^2",
    variables: [
      v("s", "perpindahan", "m"),
      v("v_0", "kecepatan awal", "m/s"),
      nonneg("t", "waktu", "s"),
      v("a", "percepatan", "m/s^2"),
    ],
    description: "Perpindahan benda dengan percepatan konstan.",
    assumptions: ["Percepatan konstan.", "Posisi awal di titik acuan (s₀ = 0)."],
    reference: P1,
    example: { solveFor: "t", values: { s: "100", v_0: "0", a: "2" } },
  },
  {
    id: "glbb-tanpa-waktu",
    name: "Persamaan GLBB tanpa waktu",
    domain: "fisika",
    topic: "Kinematika",
    equation: "v^2 = v_0^2 + 2*a*s",
    variables: [
      v("v", "kecepatan akhir", "m/s"),
      v("v_0", "kecepatan awal", "m/s"),
      v("a", "percepatan", "m/s^2"),
      v("s", "perpindahan", "m"),
    ],
    description: "Hubungan kecepatan dan perpindahan tanpa melibatkan waktu.",
    assumptions: ["Percepatan konstan."],
    reference: P1,
    example: { solveFor: "v", values: { v_0: "0", a: "9.8", s: "20" } },
  },
  {
    id: "kecepatan-rata-rata",
    name: "Kelajuan rata-rata",
    domain: "fisika",
    topic: "Kinematika",
    equation: "v = s/t",
    variables: [
      v("v", "kelajuan rata-rata", "m/s"),
      nonneg("s", "jarak tempuh", "m"),
      pos("t", "selang waktu", "s"),
    ],
    description: "Jarak tempuh dibagi waktu tempuh.",
    reference: P1,
    example: { solveFor: "v", values: { s: "150", t: "12" } },
  },
  {
    id: "jatuh-bebas",
    name: "Gerak jatuh bebas",
    domain: "fisika",
    topic: "Kinematika",
    equation: "h = 1/2*g*t^2",
    variables: [nonneg("h", "ketinggian jatuh", "m"), g(), nonneg("t", "waktu jatuh", "s")],
    description: "Benda dilepas dari keadaan diam dan jatuh bebas.",
    assumptions: ["Hambatan udara diabaikan.", "g konstan."],
    reference: P1,
    example: { solveFor: "t", values: { h: "45", g: "9.80665" } },
  },
  {
    id: "jangkauan-proyektil",
    name: "Jangkauan gerak parabola",
    domain: "fisika",
    topic: "Kinematika",
    equation: "R = v_0^2*sin(2*theta)/g",
    variables: [
      nonneg("R", "jangkauan horizontal", "m"),
      pos("v_0", "kecepatan awal", "m/s"),
      angle("theta", "sudut elevasi"),
      g(),
    ],
    description: "Jarak horizontal maksimum proyektil yang mendarat pada ketinggian awal.",
    assumptions: ["Tanah datar, hambatan udara diabaikan."],
    reference: P1,
    example: { solveFor: "R", values: { v_0: "20", theta: "45", g: "9.80665" } },
  },
  {
    id: "tinggi-maks-proyektil",
    name: "Tinggi maksimum gerak parabola",
    domain: "fisika",
    topic: "Kinematika",
    equation: "H = v_0^2*sin(theta)^2/(2*g)",
    variables: [
      nonneg("H", "tinggi maksimum", "m"),
      pos("v_0", "kecepatan awal", "m/s"),
      angle("theta", "sudut elevasi"),
      g(),
    ],
    description: "Ketinggian puncak lintasan proyektil.",
    assumptions: ["Hambatan udara diabaikan."],
    reference: P1,
    example: { solveFor: "H", values: { v_0: "20", theta: "60", g: "9.80665" } },
  },
  // ------------------------------------------------------------------ Dinamika
  {
    id: "hukum-newton-2",
    name: "Hukum II Newton",
    domain: "fisika",
    topic: "Dinamika",
    equation: "F = m*a",
    variables: [v("F", "gaya total", "N"), pos("m", "massa", "kg"), v("a", "percepatan", "m/s^2")],
    description: "Gaya total sama dengan massa dikali percepatan.",
    reference: P1,
    example: { solveFor: "a", values: { F: "20", m: "4" } },
  },
  {
    id: "gaya-berat",
    name: "Gaya berat",
    domain: "fisika",
    topic: "Dinamika",
    equation: "W = m*g",
    variables: [nonneg("W", "berat", "N"), pos("m", "massa", "kg"), g()],
    description: "Gaya gravitasi pada benda di dekat permukaan Bumi.",
    reference: P1,
    example: { solveFor: "W", values: { m: "60", g: "9.80665" } },
  },
  {
    id: "gaya-gesek",
    name: "Gaya gesek",
    domain: "fisika",
    topic: "Dinamika",
    equation: "f = mu*N",
    variables: [
      nonneg("f", "gaya gesek", "N"),
      nonneg("mu", "koefisien gesek", "", { latex: "\\mu" }),
      nonneg("N", "gaya normal", "N"),
    ],
    description: "Gaya gesek sebanding dengan gaya normal.",
    reference: P1,
    example: { solveFor: "f", values: { mu: "0.3", N: "50" } },
  },
  {
    id: "momentum",
    name: "Momentum linear",
    domain: "fisika",
    topic: "Dinamika",
    equation: "p = m*v",
    variables: [v("p", "momentum", "kg*m/s"), pos("m", "massa", "kg"), v("v", "kecepatan", "m/s")],
    description: "Massa dikali kecepatan.",
    reference: P1,
    example: { solveFor: "p", values: { m: "2", v: "3" } },
  },
  {
    id: "impuls",
    name: "Impuls",
    domain: "fisika",
    topic: "Dinamika",
    equation: "J = F*t",
    variables: [
      v("J", "impuls", "N*s"),
      v("F", "gaya rata-rata", "N"),
      pos("t", "selang waktu", "s"),
    ],
    description: "Impuls sama dengan perubahan momentum.",
    reference: P1,
    example: { solveFor: "J", values: { F: "100", t: "0.05" } },
  },
  {
    id: "gaya-sentripetal",
    name: "Gaya sentripetal",
    domain: "fisika",
    topic: "Gerak melingkar",
    equation: "F = m*v^2/r",
    variables: [
      nonneg("F", "gaya sentripetal", "N"),
      pos("m", "massa", "kg"),
      nonneg("v", "kelajuan", "m/s"),
      pos("r", "jari-jari lintasan", "m"),
    ],
    description: "Gaya yang dibutuhkan untuk gerak melingkar beraturan.",
    reference: P1,
    example: { solveFor: "F", values: { m: "1", v: "4", r: "2" } },
  },
  {
    id: "percepatan-sentripetal",
    name: "Percepatan sentripetal",
    domain: "fisika",
    topic: "Gerak melingkar",
    equation: "a = v^2/r",
    variables: [
      nonneg("a", "percepatan sentripetal", "m/s^2"),
      nonneg("v", "kelajuan", "m/s"),
      pos("r", "jari-jari", "m"),
    ],
    description: "Percepatan menuju pusat lingkaran.",
    reference: P1,
    example: { solveFor: "a", values: { v: "10", r: "5" } },
  },
  {
    id: "gravitasi-newton",
    name: "Hukum gravitasi Newton",
    domain: "fisika",
    topic: "Gravitasi",
    equation: "F = G*m_1*m_2/r^2",
    variables: [
      nonneg("F", "gaya gravitasi", "N"),
      pos("G", "konstanta gravitasi", "m^3/(kg*s^2)", { constant: "G" }),
      pos("m_1", "massa 1", "kg"),
      pos("m_2", "massa 2", "kg"),
      pos("r", "jarak pusat massa", "m"),
    ],
    description: "Gaya tarik antara dua massa.",
    reference: P1,
    example: { solveFor: "F", values: { m_1: "5.97217e24", m_2: "70", r: "6.371e6" } },
  },
  {
    id: "hukum-hooke",
    name: "Hukum Hooke",
    domain: "fisika",
    topic: "Elastisitas",
    equation: "F = k*x",
    variables: [
      v("F", "gaya pegas", "N"),
      pos("k", "konstanta pegas", "N/m"),
      v("x", "pertambahan panjang", "m"),
    ],
    description: "Gaya pegas sebanding dengan pertambahan panjang (daerah elastis).",
    reference: P1,
    example: { solveFor: "x", values: { F: "10", k: "200" } },
  },
  {
    id: "torsi",
    name: "Momen gaya (torsi)",
    domain: "fisika",
    topic: "Rotasi",
    equation: "tau = r*F*sin(theta)",
    variables: [
      v("tau", "torsi", "N*m", { latex: "\\tau" }),
      nonneg("r", "lengan gaya", "m"),
      nonneg("F", "gaya", "N"),
      angle("theta", "sudut antara r dan F"),
    ],
    description: "Kecenderungan gaya memutar benda.",
    reference: P1,
    example: { solveFor: "tau", values: { r: "0.3", F: "50", theta: "90" } },
  },
  {
    id: "periode-bandul",
    name: "Periode bandul sederhana",
    domain: "fisika",
    topic: "Getaran",
    equation: "T = 2*pi*sqrt(L/g)",
    variables: [pos("T", "periode", "s"), pos("L", "panjang tali", "m"), g()],
    description: "Periode bandul untuk simpangan kecil.",
    assumptions: ["Simpangan kecil (sin θ ≈ θ)."],
    reference: P1,
    example: { solveFor: "T", values: { L: "1", g: "9.80665" } },
  },
  {
    id: "periode-pegas",
    name: "Periode sistem pegas–massa",
    domain: "fisika",
    topic: "Getaran",
    equation: "T = 2*pi*sqrt(m/k)",
    variables: [
      pos("T", "periode", "s"),
      pos("m", "massa", "kg"),
      pos("k", "konstanta pegas", "N/m"),
    ],
    description: "Periode osilasi harmonik sederhana pegas.",
    reference: P1,
    example: { solveFor: "T", values: { m: "0.5", k: "200" } },
  },
  // ------------------------------------------------------------------ Usaha & energi
  {
    id: "energi-kinetik",
    name: "Energi kinetik",
    domain: "fisika",
    topic: "Usaha dan energi",
    equation: "E_k = 1/2*m*v^2",
    variables: [
      nonneg("E_k", "energi kinetik", "J"),
      pos("m", "massa", "kg"),
      nonneg("v", "kelajuan", "m/s"),
    ],
    description: "Energi karena gerak.",
    reference: P1,
    example: { solveFor: "v", values: { E_k: "100", m: "2" } },
  },
  {
    id: "energi-potensial",
    name: "Energi potensial gravitasi",
    domain: "fisika",
    topic: "Usaha dan energi",
    equation: "E_p = m*g*h",
    variables: [
      v("E_p", "energi potensial", "J"),
      pos("m", "massa", "kg"),
      g(),
      v("h", "ketinggian", "m"),
    ],
    description: "Energi karena posisi dalam medan gravitasi seragam.",
    reference: P1,
    example: { solveFor: "E_p", values: { m: "2", g: "9.80665", h: "10" } },
  },
  {
    id: "energi-pegas",
    name: "Energi potensial pegas",
    domain: "fisika",
    topic: "Usaha dan energi",
    equation: "E_p = 1/2*k*x^2",
    variables: [
      nonneg("E_p", "energi potensial pegas", "J"),
      pos("k", "konstanta pegas", "N/m"),
      v("x", "simpangan", "m"),
    ],
    description: "Energi tersimpan pada pegas yang teregang/tertekan.",
    reference: P1,
    example: { solveFor: "E_p", values: { k: "200", x: "0.1" } },
  },
  {
    id: "usaha",
    name: "Usaha",
    domain: "fisika",
    topic: "Usaha dan energi",
    equation: "W = F*s*cos(theta)",
    variables: [
      v("W", "usaha", "J"),
      nonneg("F", "gaya", "N"),
      nonneg("s", "perpindahan", "m"),
      angle("theta", "sudut antara gaya dan perpindahan"),
    ],
    description: "Usaha oleh gaya konstan.",
    reference: P1,
    example: { solveFor: "W", values: { F: "20", s: "5", theta: "60" } },
  },
  {
    id: "daya",
    name: "Daya",
    domain: "fisika",
    topic: "Usaha dan energi",
    equation: "P = W/t",
    variables: [v("P", "daya", "W"), v("W", "usaha/energi", "J"), pos("t", "waktu", "s")],
    description: "Laju usaha dilakukan.",
    reference: P1,
    example: { solveFor: "P", values: { W: "1200", t: "60" } },
  },
  // ------------------------------------------------------------------ Fluida
  {
    id: "massa-jenis",
    name: "Massa jenis",
    domain: "fisika",
    topic: "Fluida",
    equation: "rho = m/V",
    variables: [
      pos("rho", "massa jenis", "kg/m^3", { latex: "\\rho" }),
      pos("m", "massa", "kg"),
      pos("V", "volume", "m^3"),
    ],
    description: "Massa per satuan volume.",
    reference: P1,
    example: { solveFor: "rho", values: { m: "2", V: "0.001" } },
  },
  {
    id: "tekanan",
    name: "Tekanan",
    domain: "fisika",
    topic: "Fluida",
    equation: "P = F/A",
    variables: [
      v("P", "tekanan", "Pa"),
      v("F", "gaya tegak lurus", "N"),
      pos("A", "luas bidang", "m^2"),
    ],
    description: "Gaya per satuan luas.",
    reference: P1,
    example: { solveFor: "P", values: { F: "500", A: "0.25" } },
  },
  {
    id: "tekanan-hidrostatis",
    name: "Tekanan hidrostatis",
    domain: "fisika",
    topic: "Fluida",
    equation: "P = rho*g*h",
    variables: [
      nonneg("P", "tekanan hidrostatis", "Pa"),
      pos("rho", "massa jenis fluida", "kg/m^3", { latex: "\\rho" }),
      g(),
      nonneg("h", "kedalaman", "m"),
    ],
    description: "Tekanan oleh kolom fluida diam.",
    assumptions: ["Fluida tak termampatkan, g konstan."],
    reference: P1,
    example: { solveFor: "P", values: { rho: "1000", g: "9.80665", h: "10" } },
  },
  {
    id: "gaya-apung",
    name: "Gaya apung (Archimedes)",
    domain: "fisika",
    topic: "Fluida",
    equation: "F_A = rho*g*V",
    variables: [
      nonneg("F_A", "gaya apung", "N"),
      pos("rho", "massa jenis fluida", "kg/m^3", { latex: "\\rho" }),
      g(),
      nonneg("V", "volume tercelup", "m^3"),
    ],
    description: "Gaya ke atas sama dengan berat fluida yang dipindahkan.",
    reference: P1,
    example: { solveFor: "F_A", values: { rho: "1000", g: "9.80665", V: "0.002" } },
  },
  {
    id: "kontinuitas",
    name: "Persamaan kontinuitas",
    domain: "fisika",
    topic: "Fluida",
    equation: "A_1*v_1 = A_2*v_2",
    variables: [
      pos("A_1", "luas penampang 1", "m^2"),
      nonneg("v_1", "kecepatan 1", "m/s"),
      pos("A_2", "luas penampang 2", "m^2"),
      nonneg("v_2", "kecepatan 2", "m/s"),
    ],
    description: "Debit fluida tak termampatkan konstan.",
    reference: P1,
    example: { solveFor: "v_2", values: { A_1: "0.02", v_1: "2", A_2: "0.005" } },
  },
  {
    id: "debit",
    name: "Debit aliran",
    domain: "fisika",
    topic: "Fluida",
    equation: "Q = A*v",
    variables: [
      nonneg("Q", "debit", "m^3/s"),
      pos("A", "luas penampang", "m^2"),
      nonneg("v", "kecepatan aliran", "m/s"),
    ],
    description: "Volume fluida per satuan waktu.",
    reference: P1,
    example: { solveFor: "Q", values: { A: "0.01", v: "3" } },
  },
  // ------------------------------------------------------------------ Termodinamika
  {
    id: "kalor",
    name: "Kalor (perubahan suhu)",
    domain: "fisika",
    topic: "Termodinamika",
    equation: "Q = m*c*Delta_T",
    variables: [
      v("Q", "kalor", "J"),
      pos("m", "massa", "kg"),
      pos("c", "kalor jenis", "J/(kg*K)"),
      v("Delta_T", "perubahan suhu", "K", { latex: "\\Delta T" }),
    ],
    description: "Kalor untuk mengubah suhu zat tanpa perubahan wujud.",
    assumptions: [
      "Kalor jenis konstan pada rentang suhu tersebut.",
      "ΔT dalam K sama dengan ΔT dalam °C.",
    ],
    reference: P2,
    example: { solveFor: "Q", values: { m: "2", c: "4186", Delta_T: "30" } },
  },
  {
    id: "kalor-laten",
    name: "Kalor laten",
    domain: "fisika",
    topic: "Termodinamika",
    equation: "Q = m*L",
    variables: [v("Q", "kalor", "J"), pos("m", "massa", "kg"), pos("L", "kalor laten", "J/kg")],
    description: "Kalor untuk perubahan wujud pada suhu tetap.",
    reference: P2,
    example: { solveFor: "Q", values: { m: "0.5", L: "334000" } },
  },
  {
    id: "gas-ideal",
    name: "Persamaan gas ideal",
    domain: "fisika",
    topic: "Termodinamika",
    equation: "P*V = n*R*T",
    variables: [
      pos("P", "tekanan", "Pa"),
      pos("V", "volume", "m^3"),
      pos("n", "jumlah zat", "mol"),
      pos("R", "konstanta gas", "J/(mol*K)", { constant: "R" }),
      pos("T", "suhu mutlak", "K"),
    ],
    description: "Hubungan tekanan, volume, jumlah zat, dan suhu gas ideal.",
    assumptions: ["Gas berperilaku ideal (tekanan rendah, suhu tinggi)."],
    reference: P2,
    example: { solveFor: "V", values: { P: "101325", n: "1", T: "273.15" } },
  },
  {
    id: "muai-panjang",
    name: "Pemuaian panjang",
    domain: "fisika",
    topic: "Termodinamika",
    equation: "Delta_L = alpha*L_0*Delta_T",
    variables: [
      v("Delta_L", "pertambahan panjang", "m", { latex: "\\Delta L" }),
      pos("alpha", "koefisien muai panjang", "1/K", { latex: "\\alpha" }),
      pos("L_0", "panjang awal", "m"),
      v("Delta_T", "perubahan suhu", "K", { latex: "\\Delta T" }),
    ],
    description: "Pertambahan panjang akibat kenaikan suhu.",
    reference: P2,
    example: { solveFor: "Delta_L", values: { alpha: "1.2e-5", L_0: "10", Delta_T: "40" } },
  },
  {
    id: "efisiensi-carnot",
    name: "Efisiensi mesin Carnot",
    domain: "fisika",
    topic: "Termodinamika",
    equation: "eta = 1 - T_c/T_h",
    variables: [
      v("eta", "efisiensi", "", { latex: "\\eta", constraint: "unit-interval" }),
      pos("T_c", "suhu reservoir dingin", "K"),
      pos("T_h", "suhu reservoir panas", "K"),
    ],
    description: "Efisiensi maksimum mesin kalor.",
    assumptions: ["Suhu dalam skala mutlak (K)."],
    reference: P2,
    example: { solveFor: "eta", values: { T_c: "300", T_h: "600" } },
  },
  {
    id: "konduksi-kalor",
    name: "Laju konduksi kalor",
    domain: "teknik",
    topic: "Perpindahan panas",
    equation: "P = k*A*Delta_T/d",
    variables: [
      v("P", "laju kalor", "W"),
      pos("k", "konduktivitas termal", "W/(m*K)"),
      pos("A", "luas", "m^2"),
      v("Delta_T", "beda suhu", "K", { latex: "\\Delta T" }),
      pos("d", "tebal", "m"),
    ],
    description: "Hukum Fourier untuk konduksi satu dimensi.",
    assumptions: ["Keadaan tunak, konduktivitas konstan."],
    reference: P2,
    example: { solveFor: "P", values: { k: "0.8", A: "2", Delta_T: "20", d: "0.1" } },
  },
  // ------------------------------------------------------------------ Gelombang & optik
  {
    id: "cepat-rambat-gelombang",
    name: "Cepat rambat gelombang",
    domain: "fisika",
    topic: "Gelombang",
    equation: "v = f*lambda",
    variables: [
      pos("v", "cepat rambat", "m/s"),
      pos("f", "frekuensi", "Hz"),
      pos("lambda", "panjang gelombang", "m", { latex: "\\lambda" }),
    ],
    description: "Cepat rambat = frekuensi × panjang gelombang.",
    reference: P1,
    example: { solveFor: "lambda", values: { v: "340", f: "440" } },
  },
  {
    id: "periode-frekuensi",
    name: "Periode dan frekuensi",
    domain: "fisika",
    topic: "Gelombang",
    equation: "T = 1/f",
    variables: [pos("T", "periode", "s"), pos("f", "frekuensi", "Hz")],
    description: "Periode adalah kebalikan frekuensi.",
    reference: P1,
    example: { solveFor: "f", values: { T: "0.02" } },
  },
  {
    id: "efek-doppler",
    name: "Efek Doppler (bunyi)",
    domain: "fisika",
    topic: "Gelombang",
    equation: "f_p = f_s*(v + v_p)/(v - v_s)",
    variables: [
      pos("f_p", "frekuensi yang didengar", "Hz"),
      pos("f_s", "frekuensi sumber", "Hz"),
      pos("v", "cepat rambat bunyi", "m/s"),
      v("v_p", "kecepatan pendengar (positif jika mendekati sumber)", "m/s"),
      v("v_s", "kecepatan sumber (positif jika mendekati pendengar)", "m/s"),
    ],
    description: "Perubahan frekuensi karena gerak relatif sumber dan pendengar.",
    assumptions: [
      "Konvensi tanda: v_p positif jika pendengar mendekati sumber, v_s positif jika sumber mendekati pendengar.",
      "Medium diam.",
    ],
    reference: P1,
    example: { solveFor: "f_p", values: { f_s: "500", v: "340", v_p: "0", v_s: "20" } },
  },
  {
    id: "hukum-snellius",
    name: "Hukum Snellius",
    domain: "fisika",
    topic: "Optik",
    equation: "n_1*sin(theta_1) = n_2*sin(theta_2)",
    variables: [
      pos("n_1", "indeks bias medium 1", ""),
      angle("theta_1", "sudut datang"),
      pos("n_2", "indeks bias medium 2", ""),
      angle("theta_2", "sudut bias"),
    ],
    description: "Pembiasan cahaya pada bidang batas dua medium.",
    assumptions: ["Sudut diukur terhadap garis normal."],
    reference: P3,
    example: { solveFor: "theta_2", values: { n_1: "1", theta_1: "30", n_2: "1.5" } },
  },
  {
    id: "lensa-tipis",
    name: "Persamaan lensa/cermin",
    domain: "fisika",
    topic: "Optik",
    equation: "1/f = 1/s_o + 1/s_i",
    variables: [
      v("f", "jarak fokus", "m"),
      v("s_o", "jarak benda", "m"),
      v("s_i", "jarak bayangan", "m"),
    ],
    description: "Hubungan jarak fokus, benda, dan bayangan.",
    assumptions: [
      "Pendekatan paraksial.",
      "Konvensi tanda: bayangan nyata s_i > 0, lensa cembung/cermin cekung f > 0.",
    ],
    reference: P3,
    example: { solveFor: "s_i", values: { f: "0.1", s_o: "0.3" } },
  },
  {
    id: "perbesaran",
    name: "Perbesaran bayangan",
    domain: "fisika",
    topic: "Optik",
    equation: "M = -s_i/s_o",
    variables: [
      v("M", "perbesaran", ""),
      v("s_i", "jarak bayangan", "m"),
      v("s_o", "jarak benda", "m"),
    ],
    description: "Perbandingan tinggi bayangan dan tinggi benda.",
    reference: P3,
    example: { solveFor: "M", values: { s_i: "0.15", s_o: "0.3" } },
  },
  {
    id: "indeks-bias",
    name: "Indeks bias",
    domain: "fisika",
    topic: "Optik",
    equation: "n = c/v",
    variables: [
      pos("n", "indeks bias", ""),
      pos("c", "kecepatan cahaya", "m/s", { constant: "c" }),
      pos("v", "kecepatan cahaya dalam medium", "m/s"),
    ],
    description: "Perbandingan kecepatan cahaya di vakum dan di medium.",
    reference: P3,
    example: { solveFor: "v", values: { n: "1.5" } },
  },
  // ------------------------------------------------------------------ Listrik & magnet
  {
    id: "hukum-ohm",
    name: "Hukum Ohm",
    domain: "fisika",
    topic: "Listrik",
    equation: "V = I*R",
    variables: [v("V", "tegangan", "V"), v("I", "arus", "A"), pos("R", "hambatan", "Ω")],
    description: "Tegangan sebanding dengan arus pada penghantar ohmik.",
    reference: P2,
    example: { solveFor: "I", values: { V: "12", R: "4" } },
  },
  {
    id: "daya-listrik",
    name: "Daya listrik",
    domain: "fisika",
    topic: "Listrik",
    equation: "P = V*I",
    variables: [v("P", "daya", "W"), v("V", "tegangan", "V"), v("I", "arus", "A")],
    description: "Daya pada komponen listrik DC.",
    reference: P2,
    example: { solveFor: "P", values: { V: "220", I: "2" } },
  },
  {
    id: "hambatan-jenis",
    name: "Hambatan kawat",
    domain: "fisika",
    topic: "Listrik",
    equation: "R = rho*L/A",
    variables: [
      pos("R", "hambatan", "Ω"),
      pos("rho", "hambatan jenis", "Ω*m", { latex: "\\rho" }),
      pos("L", "panjang kawat", "m"),
      pos("A", "luas penampang", "m^2"),
    ],
    description: "Hambatan bergantung pada bahan dan geometri.",
    reference: P2,
    example: { solveFor: "R", values: { rho: "1.68e-8", L: "10", A: "1e-6" } },
  },
  {
    id: "hukum-coulomb",
    name: "Hukum Coulomb",
    domain: "fisika",
    topic: "Listrik statis",
    equation: "F = k_e*q_1*q_2/r^2",
    variables: [
      v("F", "gaya listrik (positif = tolak)", "N"),
      pos("k_e", "konstanta Coulomb", "N*m^2/C^2", { constant: "k_e" }),
      v("q_1", "muatan 1", "C"),
      v("q_2", "muatan 2", "C"),
      pos("r", "jarak", "m"),
    ],
    description: "Gaya antara dua muatan titik.",
    reference: P2,
    example: { solveFor: "F", values: { q_1: "2e-6", q_2: "3e-6", r: "0.1" } },
  },
  {
    id: "medan-listrik",
    name: "Kuat medan listrik",
    domain: "fisika",
    topic: "Listrik statis",
    equation: "E = F/q",
    variables: [
      v("E", "kuat medan listrik", "N/C"),
      v("F", "gaya", "N"),
      v("q", "muatan uji", "C"),
    ],
    description: "Gaya per satuan muatan uji.",
    reference: P2,
    example: { solveFor: "E", values: { F: "0.02", q: "4e-6" } },
  },
  {
    id: "kapasitor",
    name: "Muatan kapasitor",
    domain: "fisika",
    topic: "Listrik statis",
    equation: "Q = C*V",
    variables: [v("Q", "muatan", "C"), pos("C", "kapasitansi", "F"), v("V", "tegangan", "V")],
    description: "Muatan tersimpan sebanding dengan tegangan.",
    reference: P2,
    example: { solveFor: "Q", values: { C: "1e-6", V: "12" } },
  },
  {
    id: "energi-kapasitor",
    name: "Energi kapasitor",
    domain: "fisika",
    topic: "Listrik statis",
    equation: "E = 1/2*C*V^2",
    variables: [nonneg("E", "energi", "J"), pos("C", "kapasitansi", "F"), v("V", "tegangan", "V")],
    description: "Energi medan listrik dalam kapasitor.",
    reference: P2,
    example: { solveFor: "E", values: { C: "4.7e-6", V: "100" } },
  },
  {
    id: "gaya-lorentz",
    name: "Gaya Lorentz pada muatan",
    domain: "fisika",
    topic: "Magnet",
    equation: "F = q*v*B*sin(theta)",
    variables: [
      v("F", "gaya magnet", "N"),
      v("q", "muatan", "C"),
      nonneg("v", "kelajuan", "m/s"),
      nonneg("B", "medan magnet", "T"),
      angle("theta", "sudut antara v dan B"),
    ],
    description: "Gaya magnet pada muatan bergerak.",
    reference: P2,
    example: { solveFor: "F", values: { q: "1.602176634e-19", v: "1e6", B: "0.5", theta: "90" } },
  },
  {
    id: "gaya-kawat",
    name: "Gaya magnet pada kawat berarus",
    domain: "fisika",
    topic: "Magnet",
    equation: "F = B*I*L*sin(theta)",
    variables: [
      v("F", "gaya", "N"),
      nonneg("B", "medan magnet", "T"),
      v("I", "arus", "A"),
      pos("L", "panjang kawat", "m"),
      angle("theta", "sudut antara kawat dan B"),
    ],
    description: "Gaya Lorentz pada penghantar lurus.",
    reference: P2,
    example: { solveFor: "F", values: { B: "0.2", I: "5", L: "0.5", theta: "90" } },
  },
  {
    id: "ggl-induksi",
    name: "GGL induksi (Faraday)",
    domain: "fisika",
    topic: "Induksi",
    equation: "epsilon = N*Delta_Phi/t",
    variables: [
      v("epsilon", "GGL induksi (besar)", "V", { latex: "\\varepsilon" }),
      pos("N", "jumlah lilitan", ""),
      v("Delta_Phi", "perubahan fluks", "Wb", { latex: "\\Delta\\Phi" }),
      pos("t", "selang waktu", "s"),
    ],
    description: "Besar GGL rata-rata akibat perubahan fluks.",
    reference: P2,
    example: { solveFor: "epsilon", values: { N: "200", Delta_Phi: "0.01", t: "0.1" } },
  },
  {
    id: "transformator",
    name: "Transformator ideal",
    domain: "teknik",
    topic: "Listrik",
    equation: "V_p/V_s = N_p/N_s",
    variables: [
      pos("V_p", "tegangan primer", "V"),
      pos("V_s", "tegangan sekunder", "V"),
      pos("N_p", "lilitan primer", ""),
      pos("N_s", "lilitan sekunder", ""),
    ],
    description: "Perbandingan tegangan sama dengan perbandingan lilitan.",
    assumptions: ["Transformator ideal (efisiensi 100%)."],
    reference: P2,
    example: { solveFor: "V_s", values: { V_p: "220", N_p: "1000", N_s: "50" } },
  },
  {
    id: "konstanta-waktu-rc",
    name: "Konstanta waktu RC",
    domain: "teknik",
    topic: "Listrik",
    equation: "tau = R*C",
    variables: [
      pos("tau", "konstanta waktu", "s", { latex: "\\tau" }),
      pos("R", "hambatan", "Ω"),
      pos("C", "kapasitansi", "F"),
    ],
    description: "Waktu karakteristik pengisian/pengosongan kapasitor.",
    reference: P2,
    example: { solveFor: "tau", values: { R: "10000", C: "1e-4" } },
  },
  {
    id: "reaktansi-induktif",
    name: "Reaktansi induktif",
    domain: "teknik",
    topic: "Arus bolak-balik",
    equation: "X_L = 2*pi*f*L",
    variables: [
      nonneg("X_L", "reaktansi induktif", "Ω"),
      pos("f", "frekuensi", "Hz"),
      pos("L", "induktansi", "H"),
    ],
    description: "Hambatan semu induktor pada arus AC.",
    reference: P2,
    example: { solveFor: "X_L", values: { f: "50", L: "0.2" } },
  },
  {
    id: "reaktansi-kapasitif",
    name: "Reaktansi kapasitif",
    domain: "teknik",
    topic: "Arus bolak-balik",
    equation: "X_C = 1/(2*pi*f*C)",
    variables: [
      pos("X_C", "reaktansi kapasitif", "Ω"),
      pos("f", "frekuensi", "Hz"),
      pos("C", "kapasitansi", "F"),
    ],
    description: "Hambatan semu kapasitor pada arus AC.",
    reference: P2,
    example: { solveFor: "X_C", values: { f: "50", C: "1e-5" } },
  },
  {
    id: "resonansi-lc",
    name: "Frekuensi resonansi LC",
    domain: "teknik",
    topic: "Arus bolak-balik",
    equation: "f = 1/(2*pi*sqrt(L*C))",
    variables: [
      pos("f", "frekuensi resonansi", "Hz"),
      pos("L", "induktansi", "H"),
      pos("C", "kapasitansi", "F"),
    ],
    description: "Frekuensi saat reaktansi induktif = reaktansi kapasitif.",
    reference: P2,
    example: { solveFor: "f", values: { L: "0.001", C: "1e-6" } },
  },
  {
    id: "tegangan-rms",
    name: "Tegangan efektif (RMS)",
    domain: "teknik",
    topic: "Arus bolak-balik",
    equation: "V_rms = V_m/sqrt(2)",
    variables: [
      nonneg("V_rms", "tegangan efektif", "V", { latex: "V_{\\mathrm{rms}}" }),
      nonneg("V_m", "tegangan maksimum", "V"),
    ],
    description: "Nilai efektif tegangan sinusoidal.",
    assumptions: ["Bentuk gelombang sinusoidal murni."],
    reference: P2,
    example: { solveFor: "V_m", values: { V_rms: "220" } },
  },
  // ------------------------------------------------------------------ Fisika modern
  {
    id: "energi-foton",
    name: "Energi foton",
    domain: "fisika",
    topic: "Fisika modern",
    equation: "E = h*f",
    variables: [
      pos("E", "energi foton", "J"),
      pos("h", "konstanta Planck", "J*s", { constant: "h" }),
      pos("f", "frekuensi", "Hz"),
    ],
    description: "Energi satu foton sebanding dengan frekuensinya.",
    reference: P3,
    example: { solveFor: "E", values: { f: "5e14" } },
  },
  {
    id: "energi-foton-panjang-gelombang",
    name: "Energi foton dari panjang gelombang",
    domain: "fisika",
    topic: "Fisika modern",
    equation: "E = h*c/lambda",
    variables: [
      pos("E", "energi foton", "J"),
      pos("h", "konstanta Planck", "J*s", { constant: "h" }),
      pos("c", "kecepatan cahaya", "m/s", { constant: "c" }),
      pos("lambda", "panjang gelombang", "m", { latex: "\\lambda" }),
    ],
    description: "E = hc/λ.",
    reference: P3,
    example: { solveFor: "E", values: { lambda: "5e-7" } },
  },
  {
    id: "de-broglie",
    name: "Panjang gelombang de Broglie",
    domain: "fisika",
    topic: "Fisika modern",
    equation: "lambda = h/(m*v)",
    variables: [
      pos("lambda", "panjang gelombang", "m", { latex: "\\lambda" }),
      pos("h", "konstanta Planck", "J*s", { constant: "h" }),
      pos("m", "massa", "kg"),
      pos("v", "kelajuan", "m/s", { constraint: "below-c" }),
    ],
    description: "Sifat gelombang partikel (non-relativistik).",
    assumptions: ["v ≪ c (non-relativistik)."],
    reference: P3,
    example: { solveFor: "lambda", values: { m: "9.1093837015e-31", v: "1e6" } },
  },
  {
    id: "kesetaraan-massa-energi",
    name: "Kesetaraan massa–energi",
    domain: "fisika",
    topic: "Fisika modern",
    equation: "E = m*c^2",
    variables: [
      nonneg("E", "energi diam", "J"),
      nonneg("m", "massa", "kg"),
      pos("c", "kecepatan cahaya", "m/s", { constant: "c" }),
    ],
    description: "Energi diam setara dengan massa.",
    reference: P3,
    example: { solveFor: "E", values: { m: "0.001" } },
  },
  {
    id: "efek-fotolistrik",
    name: "Efek fotolistrik",
    domain: "fisika",
    topic: "Fisika modern",
    equation: "E_k = h*f - phi",
    variables: [
      v("E_k", "energi kinetik maksimum elektron", "J"),
      pos("h", "konstanta Planck", "J*s", { constant: "h" }),
      pos("f", "frekuensi cahaya", "Hz"),
      pos("phi", "fungsi kerja", "J", { latex: "\\phi" }),
    ],
    description: "Einstein: energi foton = fungsi kerja + energi kinetik maksimum.",
    assumptions: ["Jika hasil E_k negatif, elektron tidak terlepas (frekuensi di bawah ambang)."],
    reference: P3,
    example: { solveFor: "E_k", values: { f: "1e15", phi: "3.2e-19" } },
  },
  {
    id: "waktu-paruh",
    name: "Peluruhan radioaktif",
    domain: "fisika",
    topic: "Fisika inti",
    equation: "N = N_0*(1/2)^(t/T_half)",
    variables: [
      nonneg("N", "jumlah inti tersisa", ""),
      pos("N_0", "jumlah inti awal", ""),
      nonneg("t", "waktu", "s"),
      pos("T_half", "waktu paruh", "s", { latex: "T_{1/2}" }),
    ],
    description: "Jumlah inti radioaktif berkurang setengah setiap satu waktu paruh.",
    reference: P3,
    example: { solveFor: "N", values: { N_0: "1000", t: "10", T_half: "5" } },
  },
  {
    id: "dilatasi-waktu",
    name: "Dilatasi waktu",
    domain: "fisika",
    topic: "Relativitas",
    equation: "t = t_0/sqrt(1 - v^2/c^2)",
    variables: [
      pos("t", "selang waktu teramati", "s"),
      pos("t_0", "waktu proper", "s"),
      nonneg("v", "kelajuan relatif", "m/s", { constraint: "below-c" }),
      pos("c", "kecepatan cahaya", "m/s", { constant: "c" }),
    ],
    description: "Jam yang bergerak teramati berdetak lebih lambat.",
    reference: P3,
    example: { solveFor: "t", values: { t_0: "1", v: "2.4e8" } },
  },
  // ------------------------------------------------------------------ Astronomi
  {
    id: "hukum-kepler-3",
    name: "Hukum III Kepler",
    domain: "astronomi",
    topic: "Mekanika orbit",
    equation: "T^2 = 4*pi^2*a^3/(G*M)",
    variables: [
      pos("T", "periode orbit", "s"),
      pos("a", "sumbu semi-mayor", "m"),
      pos("G", "konstanta gravitasi", "m^3/(kg*s^2)", { constant: "G" }),
      pos("M", "massa benda pusat", "kg"),
    ],
    description: "Kuadrat periode sebanding dengan pangkat tiga sumbu semi-mayor.",
    assumptions: ["Massa satelit ≪ massa benda pusat."],
    reference: AS,
    example: { solveFor: "T", values: { a: "1.496e11", M: "1.98841e30" } },
  },
  {
    id: "kecepatan-lepas",
    name: "Kecepatan lepas",
    domain: "astronomi",
    topic: "Mekanika orbit",
    equation: "v_e = sqrt(2*G*M/r)",
    variables: [
      pos("v_e", "kecepatan lepas", "m/s"),
      pos("G", "konstanta gravitasi", "m^3/(kg*s^2)", { constant: "G" }),
      pos("M", "massa benda", "kg"),
      pos("r", "jarak dari pusat", "m"),
    ],
    description: "Kelajuan minimum untuk lepas dari gravitasi tanpa dorongan tambahan.",
    assumptions: ["Hambatan atmosfer diabaikan."],
    reference: AS,
    example: { solveFor: "v_e", values: { M: "5.97217e24", r: "6.371e6" } },
  },
  {
    id: "kecepatan-orbit",
    name: "Kecepatan orbit melingkar",
    domain: "astronomi",
    topic: "Mekanika orbit",
    equation: "v = sqrt(G*M/r)",
    variables: [
      pos("v", "kecepatan orbit", "m/s"),
      pos("G", "konstanta gravitasi", "m^3/(kg*s^2)", { constant: "G" }),
      pos("M", "massa benda pusat", "kg"),
      pos("r", "jari-jari orbit", "m"),
    ],
    description: "Kelajuan untuk orbit lingkaran.",
    reference: AS,
    example: { solveFor: "v", values: { M: "5.97217e24", r: "6.771e6" } },
  },
  {
    id: "luminositas-bintang",
    name: "Luminositas bintang (Stefan–Boltzmann)",
    domain: "astronomi",
    topic: "Astrofisika",
    equation: "L = 4*pi*R^2*sigma*T^4",
    variables: [
      pos("L", "luminositas", "W"),
      pos("R", "jari-jari bintang", "m"),
      pos("sigma", "konstanta Stefan–Boltzmann", "W/(m^2*K^4)", {
        constant: "sigma_SB",
        latex: "\\sigma",
      }),
      pos("T", "suhu efektif", "K"),
    ],
    description: "Daya total yang dipancarkan benda hitam bola.",
    assumptions: ["Bintang dimodelkan sebagai benda hitam."],
    reference: AS,
    example: { solveFor: "L", values: { R: "6.957e8", T: "5772" } },
  },
  {
    id: "hukum-wien",
    name: "Hukum pergeseran Wien",
    domain: "astronomi",
    topic: "Astrofisika",
    equation: "lambda = b/T",
    variables: [
      pos("lambda", "panjang gelombang puncak", "m", { latex: "\\lambda_{\\max}" }),
      pos("b", "konstanta Wien", "m*K", { constant: "b_W" }),
      pos("T", "suhu", "K"),
    ],
    description: "Panjang gelombang emisi puncak benda hitam.",
    reference: AS,
    example: { solveFor: "lambda", values: { T: "5772" } },
  },
  {
    id: "hukum-hubble",
    name: "Hukum Hubble–Lemaître",
    domain: "astronomi",
    topic: "Kosmologi",
    equation: "v = H_0*d",
    variables: [
      v("v", "kecepatan resesi", "km/s"),
      pos("H_0", "konstanta Hubble", "km/(s*Mpc)"),
      pos("d", "jarak", "Mpc"),
    ],
    description: "Kecepatan menjauh galaksi sebanding dengan jaraknya.",
    assumptions: [
      "Nilai H₀ masih diperdebatkan (≈67–73 km/s/Mpc); masukkan nilai yang Anda gunakan.",
    ],
    reference: AS,
    example: { solveFor: "v", values: { H_0: "70", d: "100" } },
  },
  {
    id: "modulus-jarak",
    name: "Modulus jarak",
    domain: "astronomi",
    topic: "Fotometri",
    equation: "m = M + 5*log(d) - 5",
    variables: [
      v("m", "magnitudo semu", ""),
      v("M", "magnitudo mutlak", ""),
      pos("d", "jarak (dalam parsec)", ""),
    ],
    description: "Hubungan magnitudo semu, magnitudo mutlak, dan jarak.",
    assumptions: ["d dinyatakan dalam parsec; ekstingsi antarbintang diabaikan."],
    reference: AS,
    example: { solveFor: "d", values: { m: "10", M: "4.83" } },
  },
  {
    id: "waktu-tempuh-cahaya",
    name: "Waktu tempuh cahaya",
    domain: "astronomi",
    topic: "Jarak",
    equation: "t = d/c",
    variables: [
      pos("t", "waktu tempuh", "s"),
      pos("d", "jarak", "m"),
      pos("c", "kecepatan cahaya", "m/s", { constant: "c" }),
    ],
    description: "Waktu yang dibutuhkan cahaya menempuh suatu jarak.",
    reference: AS,
    example: { solveFor: "t", values: { d: "1.496e11" } },
  },
  // ------------------------------------------------------------------ Kimia
  {
    id: "mol-massa",
    name: "Mol dari massa",
    domain: "kimia",
    topic: "Stoikiometri",
    equation: "n = m/M_r",
    variables: [
      pos("n", "jumlah zat", "mol"),
      pos("m", "massa", "g"),
      pos("M_r", "massa molar", "g/mol"),
    ],
    description: "Jumlah mol = massa / massa molar.",
    reference: CH,
    example: { solveFor: "n", values: { m: "36", M_r: "18.015" } },
  },
  {
    id: "mol-partikel",
    name: "Mol dan jumlah partikel",
    domain: "kimia",
    topic: "Stoikiometri",
    equation: "N = n*N_A",
    variables: [
      pos("N", "jumlah partikel", ""),
      pos("n", "jumlah zat", "mol"),
      pos("N_A", "bilangan Avogadro", "1/mol", { constant: "N_A" }),
    ],
    description: "Jumlah partikel = mol × bilangan Avogadro.",
    reference: CH,
    example: { solveFor: "N", values: { n: "2" } },
  },
  {
    id: "molaritas",
    name: "Molaritas",
    domain: "kimia",
    topic: "Larutan",
    equation: "C = n/V",
    variables: [
      pos("C", "molaritas", "mol/L"),
      pos("n", "jumlah zat terlarut", "mol"),
      pos("V", "volume larutan", "L"),
    ],
    description: "Mol zat terlarut per liter larutan.",
    reference: CH,
    example: { solveFor: "C", values: { n: "0.5", V: "0.25" } },
  },
  {
    id: "pengenceran",
    name: "Pengenceran",
    domain: "kimia",
    topic: "Larutan",
    equation: "C_1*V_1 = C_2*V_2",
    variables: [
      pos("C_1", "konsentrasi awal", "mol/L"),
      pos("V_1", "volume awal", "mL"),
      pos("C_2", "konsentrasi akhir", "mol/L"),
      pos("V_2", "volume akhir", "mL"),
    ],
    description: "Jumlah mol zat terlarut tetap selama pengenceran.",
    reference: CH,
    example: { solveFor: "V_1", values: { C_1: "2", C_2: "0.5", V_2: "100" } },
  },
  {
    id: "molalitas",
    name: "Molalitas",
    domain: "kimia",
    topic: "Larutan",
    equation: "b = n/m",
    variables: [
      pos("b", "molalitas", "mol/kg"),
      pos("n", "jumlah zat terlarut", "mol"),
      pos("m", "massa pelarut", "kg"),
    ],
    description: "Mol zat terlarut per kilogram pelarut.",
    reference: CH,
    example: { solveFor: "b", values: { n: "0.2", m: "0.5" } },
  },
  {
    id: "ph-asam-kuat",
    name: "pH dari konsentrasi H⁺",
    domain: "kimia",
    topic: "Asam–basa",
    equation: "P_H = -log(H_c)",
    variables: [
      v("P_H", "pH", "", { latex: "\\mathrm{pH}" }),
      pos("H_c", "[H⁺] dalam mol/L", "", { latex: "[\\mathrm{H^+}]" }),
    ],
    description: "pH adalah negatif logaritma konsentrasi ion hidrogen.",
    assumptions: [
      "Konsentrasi dipakai sebagai pendekatan aktivitas (larutan encer).",
      "[H⁺] dimasukkan sebagai angka dalam mol/L.",
    ],
    reference: CH,
    example: { solveFor: "P_H", values: { H_c: "0.001" } },
  },
  {
    id: "poh",
    name: "pOH dari konsentrasi OH⁻",
    domain: "kimia",
    topic: "Asam–basa",
    equation: "P_OH = -log(O_c)",
    variables: [
      v("P_OH", "pOH", "", { latex: "\\mathrm{pOH}" }),
      pos("O_c", "[OH⁻] dalam mol/L", "", { latex: "[\\mathrm{OH^-}]" }),
    ],
    description: "pOH adalah negatif logaritma konsentrasi ion hidroksida.",
    assumptions: ["Pada 25 °C, pH + pOH = 14."],
    reference: CH,
    example: { solveFor: "P_OH", values: { O_c: "0.01" } },
  },
  {
    id: "henderson-hasselbalch",
    name: "Persamaan Henderson–Hasselbalch",
    domain: "kimia",
    topic: "Asam–basa",
    equation: "P_H = p_Ka + log(B_c/A_c)",
    variables: [
      v("P_H", "pH larutan penyangga", "", { latex: "\\mathrm{pH}" }),
      v("p_Ka", "pKa asam lemah", "", { latex: "\\mathrm{p}K_a" }),
      pos("B_c", "[A⁻] (basa konjugasi) dalam mol/L", "", { latex: "[\\mathrm{A^-}]" }),
      pos("A_c", "[HA] (asam lemah) dalam mol/L", "", { latex: "[\\mathrm{HA}]" }),
    ],
    description: "pH larutan penyangga asam lemah dan basa konjugasinya.",
    assumptions: ["Konsentrasi cukup besar dibanding Ka; aktivitas ≈ konsentrasi."],
    reference: CH,
    example: { solveFor: "P_H", values: { p_Ka: "4.76", B_c: "0.1", A_c: "0.05" } },
  },
  {
    id: "arrhenius",
    name: "Persamaan Arrhenius",
    domain: "kimia",
    topic: "Kinetika",
    equation: "k = A*exp(-E_a/(R*T))",
    variables: [
      pos("k", "konstanta laju", "1/s"),
      pos("A", "faktor pra-eksponensial", "1/s"),
      pos("E_a", "energi aktivasi", "J/mol"),
      pos("R", "konstanta gas", "J/(mol*K)", { constant: "R" }),
      pos("T", "suhu", "K"),
    ],
    description: "Ketergantungan konstanta laju terhadap suhu.",
    assumptions: ["Satuan k dan A harus sama (di sini untuk reaksi orde satu: 1/s)."],
    reference: CH,
    example: { solveFor: "k", values: { A: "1e13", E_a: "75000", T: "298.15" } },
  },
  {
    id: "waktu-paruh-orde-1",
    name: "Waktu paruh reaksi orde satu",
    domain: "kimia",
    topic: "Kinetika",
    equation: "T_half = ln(2)/k",
    variables: [
      pos("T_half", "waktu paruh", "s", { latex: "t_{1/2}" }),
      pos("k", "konstanta laju", "1/s"),
    ],
    description: "Waktu paruh orde satu tidak bergantung konsentrasi awal.",
    reference: CH,
    example: { solveFor: "T_half", values: { k: "0.0231" } },
  },
  {
    id: "energi-bebas-gibbs",
    name: "Energi bebas Gibbs",
    domain: "kimia",
    topic: "Termokimia",
    equation: "Delta_G = Delta_H - T*Delta_S",
    variables: [
      v("Delta_G", "perubahan energi Gibbs", "J/mol", { latex: "\\Delta G" }),
      v("Delta_H", "perubahan entalpi", "J/mol", { latex: "\\Delta H" }),
      pos("T", "suhu", "K"),
      v("Delta_S", "perubahan entropi", "J/(mol*K)", { latex: "\\Delta S" }),
    ],
    description: "ΔG < 0 berarti reaksi spontan pada T dan P tetap.",
    reference: CH,
    example: { solveFor: "Delta_G", values: { Delta_H: "-92200", T: "298.15", Delta_S: "-198.7" } },
  },
  {
    id: "nernst",
    name: "Persamaan Nernst",
    domain: "kimia",
    topic: "Elektrokimia",
    equation: "E = E_0 - R*T/(z*F)*ln(Q)",
    variables: [
      v("E", "potensial sel", "V"),
      v("E_0", "potensial sel standar", "V", { latex: "E^\\circ" }),
      pos("R", "konstanta gas", "J/(mol*K)", { constant: "R" }),
      pos("T", "suhu", "K"),
      pos("z", "jumlah elektron", ""),
      pos("F", "konstanta Faraday", "C/mol", { constant: "F" }),
      pos("Q", "kuosien reaksi", ""),
    ],
    description: "Potensial sel pada kondisi non-standar.",
    reference: CH,
    example: { solveFor: "E", values: { E_0: "1.10", T: "298.15", z: "2", Q: "0.01" } },
  },
  {
    id: "elektrolisis-faraday",
    name: "Hukum Faraday elektrolisis",
    domain: "kimia",
    topic: "Elektrokimia",
    equation: "m = I*t*M_r/(z*F)",
    variables: [
      nonneg("m", "massa zat", "g"),
      pos("I", "arus", "A"),
      nonneg("t", "waktu", "s"),
      pos("M_r", "massa molar", "g/mol"),
      pos("z", "jumlah elektron per ion", ""),
      pos("F", "konstanta Faraday", "C/mol", { constant: "F" }),
    ],
    description: "Massa zat yang diendapkan sebanding dengan muatan listrik.",
    reference: CH,
    example: { solveFor: "m", values: { I: "2", t: "3600", M_r: "63.546", z: "2" } },
  },
  {
    id: "rendemen",
    name: "Persen hasil (rendemen)",
    domain: "kimia",
    topic: "Stoikiometri",
    equation: "Y = m_a/m_t*100",
    variables: [
      nonneg("Y", "persen hasil (%)", ""),
      nonneg("m_a", "hasil nyata", "g"),
      pos("m_t", "hasil teoretis", "g"),
    ],
    description: "Perbandingan hasil nyata terhadap hasil teoretis.",
    reference: CH,
    example: { solveFor: "Y", values: { m_a: "8.5", m_t: "10" } },
  },
  // ------------------------------------------------------------------ Teknik
  {
    id: "tegangan-mekanik",
    name: "Tegangan (stress)",
    domain: "teknik",
    topic: "Mekanika bahan",
    equation: "sigma = F/A",
    variables: [
      v("sigma", "tegangan normal", "Pa", { latex: "\\sigma" }),
      v("F", "gaya aksial", "N"),
      pos("A", "luas penampang", "m^2"),
    ],
    description: "Gaya per satuan luas penampang.",
    reference: P1,
    example: { solveFor: "sigma", values: { F: "10000", A: "0.0005" } },
  },
  {
    id: "regangan",
    name: "Regangan (strain)",
    domain: "teknik",
    topic: "Mekanika bahan",
    equation: "epsilon = Delta_L/L_0",
    variables: [
      v("epsilon", "regangan", "", { latex: "\\varepsilon" }),
      v("Delta_L", "perubahan panjang", "m", { latex: "\\Delta L" }),
      pos("L_0", "panjang awal", "m"),
    ],
    description: "Perubahan panjang relatif.",
    reference: P1,
    example: { solveFor: "epsilon", values: { Delta_L: "0.001", L_0: "2" } },
  },
  {
    id: "modulus-young",
    name: "Modulus Young",
    domain: "teknik",
    topic: "Mekanika bahan",
    equation: "Y = sigma/epsilon",
    variables: [
      pos("Y", "modulus Young", "Pa"),
      v("sigma", "tegangan", "Pa", { latex: "\\sigma" }),
      v("epsilon", "regangan", "", { latex: "\\varepsilon" }),
    ],
    description: "Kekakuan bahan pada daerah elastis.",
    reference: P1,
    example: { solveFor: "Y", values: { sigma: "2e8", epsilon: "0.001" } },
  },
  {
    id: "daya-poros",
    name: "Daya poros berputar",
    domain: "teknik",
    topic: "Mesin",
    equation: "P = 2*pi*f*tau",
    variables: [
      v("P", "daya", "W"),
      nonneg("f", "kecepatan putar", "rpm"),
      v("tau", "torsi", "N*m", { latex: "\\tau" }),
    ],
    description: "Daya = torsi × kecepatan sudut (ω = 2πf).",
    reference: P1,
    example: { solveFor: "P", values: { f: "1500", tau: "100" } },
  },
  {
    id: "rasio-roda-gigi",
    name: "Rasio roda gigi",
    domain: "teknik",
    topic: "Mesin",
    equation: "n_1*Z_1 = n_2*Z_2",
    variables: [
      pos("n_1", "putaran roda penggerak", "rpm"),
      pos("Z_1", "jumlah gigi penggerak", ""),
      pos("n_2", "putaran roda digerakkan", "rpm"),
      pos("Z_2", "jumlah gigi digerakkan", ""),
    ],
    description: "Kecepatan keliling kedua roda gigi sama.",
    reference: P1,
    example: { solveFor: "n_2", values: { n_1: "1200", Z_1: "20", Z_2: "60" } },
  },
  {
    id: "efisiensi",
    name: "Efisiensi",
    domain: "teknik",
    topic: "Energi",
    equation: "eta = P_out/P_in",
    variables: [
      v("eta", "efisiensi (0–1)", "", { latex: "\\eta", constraint: "unit-interval" }),
      nonneg("P_out", "daya keluaran", "W", { latex: "P_{\\mathrm{out}}" }),
      pos("P_in", "daya masukan", "W", { latex: "P_{\\mathrm{in}}" }),
    ],
    description: "Perbandingan energi/daya berguna dengan masukan.",
    reference: P1,
    example: { solveFor: "eta", values: { P_out: "750", P_in: "1000" } },
  },
  {
    id: "momen-balok-merata",
    name: "Momen maksimum balok (beban merata)",
    domain: "teknik",
    topic: "Struktur",
    equation: "M = w*L^2/8",
    variables: [
      nonneg("M", "momen lentur maksimum", "N*m"),
      nonneg("w", "beban merata", "N/m"),
      pos("L", "bentang", "m"),
    ],
    description: "Balok sederhana (dua tumpuan) dengan beban merata penuh.",
    assumptions: ["Tumpuan sendi–rol, beban merata sepanjang bentang."],
    reference: P1,
    example: { solveFor: "M", values: { w: "5000", L: "6" } },
  },
  {
    id: "momen-balok-terpusat",
    name: "Momen maksimum balok (beban terpusat di tengah)",
    domain: "teknik",
    topic: "Struktur",
    equation: "M = P*L/4",
    variables: [
      nonneg("M", "momen lentur maksimum", "N*m"),
      nonneg("P", "beban terpusat", "N"),
      pos("L", "bentang", "m"),
    ],
    description: "Balok sederhana dengan beban titik di tengah bentang.",
    assumptions: ["Tumpuan sendi–rol, beban tepat di tengah."],
    reference: P1,
    example: { solveFor: "M", values: { P: "20000", L: "4" } },
  },
  // ------------------------------------------------------------------ Geometri
  {
    id: "luas-lingkaran",
    name: "Luas lingkaran",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "A = pi*r^2",
    variables: [pos("A", "luas", "m^2"), pos("r", "jari-jari", "m")],
    description: "Luas daerah lingkaran.",
    reference: AL,
    example: { solveFor: "A", values: { r: "7" } },
  },
  {
    id: "keliling-lingkaran",
    name: "Keliling lingkaran",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "K = 2*pi*r",
    variables: [pos("K", "keliling", "m"), pos("r", "jari-jari", "m")],
    description: "Panjang busur lingkaran penuh.",
    reference: AL,
    example: { solveFor: "K", values: { r: "7" } },
  },
  {
    id: "luas-persegi-panjang",
    name: "Luas persegi panjang",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "A = p*l",
    variables: [pos("A", "luas", "m^2"), pos("p", "panjang", "m"), pos("l", "lebar", "m")],
    description: "Panjang × lebar.",
    reference: AL,
    example: { solveFor: "A", values: { p: "8", l: "5" } },
  },
  {
    id: "keliling-persegi-panjang",
    name: "Keliling persegi panjang",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "K = 2*(p + l)",
    variables: [pos("K", "keliling", "m"), pos("p", "panjang", "m"), pos("l", "lebar", "m")],
    description: "Dua kali jumlah panjang dan lebar.",
    reference: AL,
    example: { solveFor: "K", values: { p: "8", l: "5" } },
  },
  {
    id: "luas-segitiga",
    name: "Luas segitiga",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "A = 1/2*a*t",
    variables: [pos("A", "luas", "m^2"), pos("a", "alas", "m"), pos("t", "tinggi", "m")],
    description: "Setengah alas × tinggi.",
    reference: AL,
    example: { solveFor: "A", values: { a: "10", t: "6" } },
  },
  {
    id: "luas-trapesium",
    name: "Luas trapesium",
    domain: "geometri",
    topic: "Bangun datar",
    equation: "A = 1/2*(a + b)*t",
    variables: [
      pos("A", "luas", "m^2"),
      pos("a", "sisi sejajar 1", "m"),
      pos("b", "sisi sejajar 2", "m"),
      pos("t", "tinggi", "m"),
    ],
    description: "Setengah jumlah sisi sejajar × tinggi.",
    reference: AL,
    example: { solveFor: "A", values: { a: "6", b: "10", t: "4" } },
  },
  {
    id: "pythagoras",
    name: "Teorema Pythagoras",
    domain: "geometri",
    topic: "Segitiga",
    equation: "c^2 = a^2 + b^2",
    variables: [
      pos("c", "sisi miring", "m"),
      pos("a", "sisi tegak 1", "m"),
      pos("b", "sisi tegak 2", "m"),
    ],
    description:
      "Pada segitiga siku-siku, kuadrat hipotenusa sama dengan jumlah kuadrat sisi lainnya.",
    reference: AL,
    example: { solveFor: "c", values: { a: "3", b: "4" } },
  },
  {
    id: "volume-bola",
    name: "Volume bola",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "V = 4/3*pi*r^3",
    variables: [pos("V", "volume", "m^3"), pos("r", "jari-jari", "m")],
    description: "Volume bola.",
    reference: AL,
    example: { solveFor: "V", values: { r: "3" } },
  },
  {
    id: "luas-permukaan-bola",
    name: "Luas permukaan bola",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "L = 4*pi*r^2",
    variables: [pos("L", "luas permukaan", "m^2"), pos("r", "jari-jari", "m")],
    description: "Luas kulit bola.",
    reference: AL,
    example: { solveFor: "L", values: { r: "3" } },
  },
  {
    id: "volume-tabung",
    name: "Volume tabung",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "V = pi*r^2*t",
    variables: [
      pos("V", "volume", "m^3"),
      pos("r", "jari-jari alas", "m"),
      pos("t", "tinggi", "m"),
    ],
    description: "Luas alas × tinggi.",
    reference: AL,
    example: { solveFor: "V", values: { r: "7", t: "10" } },
  },
  {
    id: "luas-permukaan-tabung",
    name: "Luas permukaan tabung",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "L = 2*pi*r*(r + t)",
    variables: [
      pos("L", "luas permukaan", "m^2"),
      pos("r", "jari-jari", "m"),
      pos("t", "tinggi", "m"),
    ],
    description: "Dua alas ditambah selimut.",
    reference: AL,
    example: { solveFor: "L", values: { r: "7", t: "10" } },
  },
  {
    id: "volume-kerucut",
    name: "Volume kerucut",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "V = 1/3*pi*r^2*t",
    variables: [
      pos("V", "volume", "m^3"),
      pos("r", "jari-jari alas", "m"),
      pos("t", "tinggi", "m"),
    ],
    description: "Sepertiga volume tabung dengan alas dan tinggi sama.",
    reference: AL,
    example: { solveFor: "V", values: { r: "3", t: "4" } },
  },
  {
    id: "volume-balok",
    name: "Volume balok",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "V = p*l*t",
    variables: [
      pos("V", "volume", "m^3"),
      pos("p", "panjang", "m"),
      pos("l", "lebar", "m"),
      pos("t", "tinggi", "m"),
    ],
    description: "Panjang × lebar × tinggi.",
    reference: AL,
    example: { solveFor: "V", values: { p: "5", l: "4", t: "3" } },
  },
  {
    id: "volume-kubus",
    name: "Volume kubus",
    domain: "geometri",
    topic: "Bangun ruang",
    equation: "V = s^3",
    variables: [pos("V", "volume", "m^3"), pos("s", "rusuk", "m")],
    description: "Rusuk pangkat tiga.",
    reference: AL,
    example: { solveFor: "s", values: { V: "27" } },
  },
  {
    id: "jarak-dua-titik",
    name: "Jarak dua titik",
    domain: "geometri",
    topic: "Geometri koordinat",
    equation: "d = sqrt((x_2 - x_1)^2 + (y_2 - y_1)^2)",
    variables: [
      nonneg("d", "jarak", ""),
      v("x_1", "x titik 1", ""),
      v("y_1", "y titik 1", ""),
      v("x_2", "x titik 2", ""),
      v("y_2", "y titik 2", ""),
    ],
    description: "Rumus jarak Euclid pada bidang.",
    reference: AL,
    example: { solveFor: "d", values: { x_1: "1", y_1: "2", x_2: "4", y_2: "6" } },
  },
  {
    id: "gradien-garis",
    name: "Gradien garis",
    domain: "geometri",
    topic: "Geometri koordinat",
    equation: "m = (y_2 - y_1)/(x_2 - x_1)",
    variables: [
      v("m", "gradien", ""),
      v("x_1", "x titik 1", ""),
      v("y_1", "y titik 1", ""),
      v("x_2", "x titik 2", ""),
      v("y_2", "y titik 2", ""),
    ],
    description: "Kemiringan garis melalui dua titik.",
    reference: AL,
    example: { solveFor: "m", values: { x_1: "1", y_1: "2", x_2: "4", y_2: "8" } },
  },
];

export const FORMULA_BY_ID: Record<string, FormulaDef> = Object.fromEntries(
  FORMULAS.map((f) => [f.id, f]),
);

export const DOMAIN_LABELS: Record<FormulaDomain, string> = {
  fisika: "Fisika",
  kimia: "Kimia",
  astronomi: "Astronomi",
  teknik: "Teknik",
  geometri: "Geometri",
};
